#!/bin/bash

cd ./vaw-gan-f0

python convert-vawgan-separate-f0.py #Please customize your checkpoint dir in python script: --checkpoint "./log/train/[TIMESETP]/model.ckpt-[MODEL ID]"
python convert-vawgan-separate-f0.py #Please customize your checkpoint dir in python script: --checkpoint "./log/train/[TIMESETP]/model.ckpt-[MODEL ID]"
python save_f0.py

cd ../vaw-gan

python test-condition.py
python convert-vawgan-cwt.py #Please customize your checkpoint dir in python script: --checkpoint "./log/train/[TIMESETP]/model.ckpt-[MODEL ID]"
python convert-vawgan-cwt.py #Please customize your checkpoint dir in python script: --checkpoint "./log/train/[TIMESETP]/model.ckpt-[MODEL ID]"




#!/bin/bash

cd ./vaw-gan-f0

python analyzer_f0.py
python build_f0.py
python main-vawgan-f0.py



#!/bin/bash

cd ./vaw-gan

python analyzer_sp.py
python build.py
python main-vawgan.py


